List<Map<String, dynamic>> menuItems = [
  {
    'id': '1',
    'image': 'assets/images/menu/menu_1.png',
    'name': 'menu1',
    'price': 168000,
    'category': 'category1',
  },
  {
    'id': '2',
    'image': 'assets/images/menu/menu_2.png',
    'name': 'menu2',
    'price': 88000,
    'category': 'category1',
  },
  {
    'id': '3',
    'image': 'assets/images/menu/menu_3.png',
    'name': 'menu3',
    'price': 128000,
    'category': 'category1',
  },
  {
    'id': '4',
    'image': 'assets/images/menu/menu_4.png',
    'name': 'menu4',
    'price': 108000,
    'category': 'category1',
  },
  {
    'id': '5',
    'image': 'assets/images/menu/menu_5.png',
    'name': 'menu5',
    'price': 86000,
    'category': 'category1',
  },
  {
    'id': '6',
    'image': 'assets/images/menu/menu_6.png',
    'name': 'menu6',
    'type': {'0': 'method1', '1': 'method2', '2': 'method3', '3': 'method4'},
    'price': {
      '0': 'string_price',
      '1': 'string_price',
      '2': 'string_price',
      '3': 'string_price'
    },
    'category': 'category2',
  },
  {
    'id': '7',
    'image': 'assets/images/menu/menu_7.png',
    'name': 'menu7',
    'type': {'0': 'method1', '1': 'method2', '2': 'method3', '3': 'method4'},
    'price': {
      '0': 'string_price',
      '1': 'string_price',
      '2': 'string_price',
      '3': 'string_price'
    },
    'category': 'category2',
  },
  {
    'id': '8',
    'image': 'assets/images/menu/menu_8.png',
    'name': 'menu8',
    'type': {'0': 'method1', '1': 'method2', '2': 'method3', '3': 'method4'},
    'price': {
      '0': 'string_price',
      '1': 'string_price',
      '2': 'string_price',
      '3': 'string_price'
    },
    'category': 'category2',
  },
  {
    'id': '9',
    'image': 'assets/images/menu/menu_9.png',
    'name': 'menu9',
    'type': {'0': 'method3', '1': 'method5'},
    'price': {'0': 'string_price', '1': 'string_price'},
    'category': 'category2',
  },
  {
    'id': '10',
    'image': 'assets/images/menu/menu_10.png',
    'name': 'menu10',
    'type': {'0': 'method14', '1': 'method6'},
    'price': {'0': 'string_price', '1': 'string_price'},
    'category': 'category2',
  },
  {
    'id': '11',
    'image': 'assets/images/menu/menu_11.png',
    'name': 'menu11',
    'type': {
      '0': 'method6',
      '1': 'method5',
      '2': 'method8',
      '3': 'method9',
      '4': 'method10',
      '5': 'method11'
    },
    'price': {
      '0': 'string_price',
      '1': 'string_price',
      '2': 'string_price',
      '3': 'string_price',
      '4': 'string_price',
      '5': 'string_price'
    },
    'category': 'category2',
  },
  {
    'id': '12',
    'image': 'assets/images/menu/menu_12.png',
    'name': 'menu12',
    'type': {'0': 'method12', '1': 'method13'},
    'price': {'0': 'string_price', '1': 'string_price'},
    'category': 'category2',
  },
  {
    'id': '13',
    'image': 'assets/images/menu/menu_13.png',
    'name': 'menu13',
    'type': {'0': 'method14', '1': 'method15', '2': 'method13', '3': 'method7'},
    'price': {
      '0': 'string_price',
      '1': 'string_price',
      '2': 'string_price',
      '3': 'string_price'
    },
    'category': 'category2',
  },
  {
    'id': '14',
    'image': 'assets/images/menu/menu_14.png',
    'name': 'menu14',
    'type': {'0': 'method16', '1': 'method5'},
    'price': {'0': 13800, '1': 13800},
    'category': 'category2',
  },
  {
    'id': '15',
    'image': 'assets/images/menu/menu_15.png',
    'name': 'menu15',
    'type': 'method6',
    'price': 16800,
    'category': 'category2',
  },
  {
    'id': '16',
    'image': 'assets/images/menu/menu_16.png',
    'name': 'menu16',
    'type': {'0': 'method13', '1': 'method17', '2': 'method8', '3': 'method18'},
    'price': {
      '0': 'string_price',
      '1': 'string_price',
      '2': 'string_price',
      '3': 'string_price'
    },
    'category': 'category2',
  },
  {
    'id': '17',
    'image': 'assets/images/menu/menu_17.png',
    'name': 'menu17',
    'type': {'0': 'method14', '1': 'method6'},
    'price': {'0': 'string_price', '1': 'string_price'},
    'category': 'category2',
  },
  {
    'id': '18',
    'image': 'assets/images/menu/menu_18.png',
    'name': 'menu18',
    'type': {'0': 'method19', '1': 'method11', '2': 'method16'},
    'price': {'0': 'string_price', '1': 'string_price', '2': 'string_price'},
    'category': 'category2',
  },
  {
    'id': '19',
    'image': 'assets/images/menu/menu_19.png',
    'name': 'menu19',
    'type': {
      '0': 'method11',
      '1': 'method15',
      '2': 'method19',
      '3': 'method20',
      '4': 'method21'
    },
    'price': {
      '0': 'string_price',
      '1': 'string_price',
      '2': 'string_price',
      '3': 'string_price',
      '4': 'string_price'
    },
    'category': 'category2',
  },
  {
    'id': '20',
    'image': 'assets/images/menu/menu_20.png',
    'name': 'menu20',
    'type': {'0': 'method8', '1': 'method1', '2': 'method17', '3': 'method20'},
    'price': {
      '0': 'string_price',
      '1': 'string_price',
      '2': 'string_price',
      '3': 'string_price'
    },
    'category': 'category2',
  },
  {
    'id': '21',
    'image': 'assets/images/menu/menu_21.png',
    'name': 'menu21',
    'price': 158000,
    'category': 'category3',
  },
  {
    'id': '22',
    'image': 'assets/images/menu/menu_22.png',
    'name': 'menu22',
    'price': 568000,
    'detail': 'detail',
    'category': 'category3',
  },
  {
    'id': '23',
    'image': 'assets/images/menu/menu_23.png',
    'name': 'menu23',
    'price': 88000,
    'category': 'category3',
  },
  {
    'id': '24',
    'image': 'assets/images/menu/menu_24.png',
    'name': 'menu24',
    'price': 42800,
    'category': 'category3',
  },
  {
    'id': '25',
    'image': 'assets/images/menu/menu_25.png',
    'name': 'menu25',
    'price': 188000,
    'category': 'category3',
  },
  {
    'id': '26',
    'image': 'assets/images/menu/menu_26.png',
    'name': 'menu26',
    'price': 52800,
    'category': 'category3',
  },
  {
    'id': '27',
    'image': 'assets/images/menu/menu_27.png',
    'name': 'menu27',
    'type': {'0': 'method32', '1': 'method33'},
    'price': {'0': 35800, '1': 66800},
    'category': 'category3',
  },
  {
    'id': '28',
    'image': 'assets/images/menu/menu_28.png',
    'name': 'menu28',
    'price': 42800,
    'category': 'category3',
  },
  {
    'id': '29',
    'image': 'assets/images/menu/menu_29.png',
    'name': 'menu29',
    'price': 52800,
    'category': 'category3',
  },
  {
    'id': '30',
    'image': 'assets/images/menu/menu_30.png',
    'name': 'menu30',
    'price': 22800,
    'category': 'category3',
  },
  {
    'id': '31',
    'image': 'assets/images/menu/menu_31.png',
    'name': 'menu31',
    'price': 42800,
    'category': 'category3',
  },
  {
    'id': '32',
    'image': 'assets/images/menu/menu_32.png',
    'name': 'menu32',
    'price': 42800,
    'category': 'category3',
  },
  {
    'id': '33',
    'image': 'assets/images/menu/menu_33.png',
    'name': 'menu33',
    'price': 32800,
    'category': 'category3',
  },
  {
    'id': '34',
    'image': 'assets/images/menu/menu_34.png',
    'name': 'menu34',
    'price': 56800,
    'category': 'category3',
  },
  {
    'id': '35',
    'image': 'assets/images/menu/menu_35.png',
    'name': 'menu35',
    'price': 52800,
    'category': 'category3',
  },
  // {
  //   'id': '36',
  //   'image': 'assets/images/menu/menu_36.png',
  //   'name': '',
  //   'price': 26800,
  //   'category': 'category3',
  // },
  {
    'id': '37',
    'image': 'assets/images/menu/menu_37.png',
    'name': 'menu37',
    'price': 19800,
    'category': 'category3',
  },
  {
    'id': '38',
    'image': 'assets/images/menu/menu_38.png',
    'name': 'menu38',
    'price': 36800,
    'category': 'category3',
  },
  {
    'id': '39',
    'image': 'assets/images/menu/menu_39.png',
    'name': 'menu39',
    'price': 42800,
    'category': 'category3',
  },
  {
    'id': '40',
    'image': 'assets/images/menu/menu_40.png',
    'name': 'menu40',
    'price': 32800,
    'category': 'category3',
  },
  // {
  //   'id': '41',
  //   'image': 'assets/images/menu/menu_41.png',
  //   'name': '',
  //   'price': 42800,
  //   'category': 'category3',
  // },
  {
    'id': '42',
    'image': 'assets/images/menu/menu_42.png',
    'name': 'menu42',
    'price': 18000,
    'category': 'category3',
  },
  {
    'id': '43',
    'image': 'assets/images/menu/menu_43.png',
    'name': 'menu43',
    'price': 22800,
    'category': 'category3',
  },
  {
    'id': '44',
    'image': 'assets/images/menu/menu_44.png',
    'name': 'menu44',
    'price': 26800,
    'category': 'category3',
  },
  {
    'id': '45',
    'image': 'assets/images/menu/menu_45.png',
    'name': 'menu45',
    'price': 18000,
    'category': 'category3',
  },
  {
    'id': '46',
    'image': 'assets/images/menu/menu_46.png',
    'name': 'menu46',
    'type': {
      '0': 'fish1',
      '1': 'fish2',
      '2': 'fish3',
      '3': 'fish4',
      '4': 'fish5'
    },
    'price': {
      '0': 66800,
      '1': 'string_price',
      '2': 'string_price',
      '3': 'string_price',
      '4': 'string_price'
    },
    'category': 'category4',
  },
  {
    'id': '47',
    'image': 'assets/images/menu/menu_47.png',
    'name': 'menu47',
    'type': {'0': 'fish1', '1': 'fish4', '2': 'fish5', '3': 'fish3'},
    'price': {
      '0': 66800,
      '1': 'string_price',
      '2': 'string_price',
      '3': 'string_price'
    },
    'category': 'category4',
  },
  {
    'id': '48',
    'image': 'assets/images/menu/menu_48.png',
    'name': 'menu48',
    'price': 88000,
    'category': 'category5',
  },
  {
    'id': '49',
    'image': 'assets/images/menu/menu_49.png',
    'name': 'menu49',
    'price': 56800,
    'category': 'category5',
  },
  {
    'id': '50',
    'image': 'assets/images/menu/menu_50.png',
    'name': 'menu50',
    'price': 418000,
    'category': 'category5',
  },
  {
    'id': '51',
    'image': 'assets/images/menu/menu_51.png',
    'name': 'menu51',
    'price': 268000,
    'category': 'category5',
  },
  {
    'id': '52',
    'image': 'assets/images/menu/menu_52.png',
    'name': 'menu52',
    'price': 42800,
    'category': 'category5',
  },
  {
    'id': '53',
    'image': 'assets/images/menu/menu_53.png',
    'name': 'menu53',
    'price': 66800,
    'category': 'category5',
  },
  {
    'id': '54',
    'image': 'assets/images/menu/menu_54.png',
    'name': 'menu54',
    'price': 42800,
    'category': 'category5',
  },
  {
    'id': '55',
    'image': 'assets/images/menu/menu_55.png',
    'name': 'menu55',
    'price': 88000,
    'category': 'category5',
  },
  {
    'id': '56',
    'image': 'assets/images/menu/menu_56.png',
    'name': 'menu56',
    'price': 72800,
    'category': 'category5',
  },
  {
    'id': '57',
    'image': 'assets/images/menu/menu_57.png',
    'name': 'menu57',
    'price': 228000,
    'category': 'category5',
  },
  {
    'id': '58',
    'image': 'assets/images/menu/menu_58.png',
    'name': 'menu58',
    'price': 42800,
    'category': 'category5',
  },
  // {
  //   'id': '59',
  //   'image': 'assets/images/menu/menu_59.png',
  //   'name': 'menu59',
  //   'price': 168000,
  //   'category': 'category5',
  // },
  {
    'id': '60',
    'image': 'assets/images/menu/menu_60.png',
    'name': 'menu60',
    'price': 42800,
    'category': 'category5',
  },
  {
    'id': '61',
    'image': 'assets/images/menu/menu_61.png',
    'name': 'menu61',
    'price': 158000,
    'category': 'category5',
  },
  {
    'id': '62',
    'image': 'assets/images/menu/menu_62.png',
    'name': 'menu62',
    'price': 74800,
    'category': 'category5',
  },
  {
    'id': '63',
    'image': 'assets/images/menu/menu_63.png',
    'name': 'menu63',
    'price': 198000,
    'category': 'category5',
  },
  {
    'id': '64',
    'image': 'assets/images/menu/menu_64.png',
    'name': 'menu64',
    'price': 42800,
    'category': 'category5',
  },
  {
    'id': '65',
    'image': 'assets/images/menu/menu_65.png',
    'name': 'menu65',
    'price': 128000,
    'category': 'category5',
  },
  {
    'id': '66',
    'image': 'assets/images/menu/menu_66.png',
    'name': 'menu66',
    'price': 78000,
    'category': 'category5',
  },
  {
    'id': '67',
    'image': 'assets/images/menu/menu_67.png',
    'name': 'menu67',
    'price': 118000,
    'category': 'category5',
  },
  {
    'id': '68',
    'image': 'assets/images/menu/menu_68.png',
    'name': 'menu68',
    'price': 32800,
    'category': 'category5',
  },
  {
    'id': '69',
    'image': 'assets/images/menu/menu_69.png',
    'name': 'menu69',
    'price': 36800,
    'category': 'category5',
  },
  {
    'id': '70',
    'image': 'assets/images/menu/menu_70.png',
    'name': 'menu70',
    'price': 58000,
    'category': 'category5',
  },
  {
    'id': '71',
    'image': 'assets/images/menu/menu_71.png',
    'name': 'menu71',
    'price': 68000,
    'category': 'category5',
  },
  {
    'id': '72',
    'image': 'assets/images/menu/menu_72.png',
    'name': 'menu72',
    'price': 56800,
    'category': 'category5',
  },
  {
    'id': '73',
    'image': 'assets/images/menu/menu_73.png',
    'name': 'menu73',
    'price': 42800,
    'category': 'category5',
  },
  {
    'id': '74',
    'image': 'assets/images/menu/menu_74.png',
    'name': 'menu74',
    'price': 78000,
    'category': 'category5',
  },
  {
    'id': '75',
    'image': 'assets/images/menu/menu_75.png',
    'name': 'menu75',
    'price': 76800,
    'category': 'category5',
  },
  {
    'id': '76',
    'image': 'assets/images/menu/menu_76.png',
    'name': 'menu76',
    'price': 68000,
    'category': 'category5',
  },
  {
    'id': '77',
    'image': 'assets/images/menu/menu_77.png',
    'name': 'menu77',
    'price': 42800,
    'category': 'category5',
  },
  {
    'id': '78',
    'image': 'assets/images/menu/menu_78.png',
    'name': 'menu78',
    'price': 46800,
    'category': 'category5',
  },
  {
    'id': '79',
    'image': 'assets/images/menu/menu_79.png',
    'name': 'menu79',
    'price': 148000,
    'category': 'category5',
  },
  {
    'id': '80',
    'image': 'assets/images/menu/menu_80.png',
    'name': 'menu80',
    'price': 36000,
    'category': 'category5',
  },
  {
    'id': '81',
    'image': 'assets/images/menu/menu_81.png',
    'name': 'menu81',
    'price': 68000,
    'category': 'category5',
  },
  {
    'id': '82',
    'image': 'assets/images/menu/menu_82.png',
    'name': 'menu82',
    'price': 58000,
    'category': 'category5',
  },
  {
    'id': '83',
    'image': 'assets/images/menu/menu_83.png',
    'name': 'menu83',
    'price': 68000,
    'category': 'category5',
  },
  {
    'id': '84',
    'image': 'assets/images/menu/menu_84.png',
    'name': 'menu84',
    'price': 42800,
    'category': 'category5',
  },
  {
    'id': '85',
    'image': 'assets/images/menu/menu_85.png',
    'name': 'menu85',
    'price': 56800,
    'category': 'category5',
  },
  {
    'id': '86',
    'image': 'assets/images/menu/menu_86.png',
    'name': 'menu86',
    'price': 6800,
    'category': 'category5',
  },
  {
    'id': '87',
    'image': 'assets/images/menu/menu_87.png',
    'name': 'menu87',
    'price': 56800,
    'category': 'category5',
  },
  {
    'id': '88',
    'image': 'assets/images/menu/menu_88.png',
    'name': 'menu88',
    'price': 78000,
    'category': 'category5',
  },
  {
    'id': '89',
    'image': 'assets/images/menu/menu_89.png',
    'name': 'menu89',
    'price': 58000,
    'category': 'category5',
  },
  {
    'id': '90',
    'image': 'assets/images/menu/menu_90.png',
    'name': 'menu90',
    'price': 42800,
    'category': 'category5',
  },
  {
    'id': '91',
    'image': 'assets/images/menu/menu_91.png',
    'name': 'menu91',
    'price': 42800,
    'category': 'category5',
  },
  {
    'id': '92',
    'image': 'assets/images/menu/menu_92.png',
    'name': 'menu92',
    'price': 36800,
    'category': 'category5',
  },
  {
    'id': '93',
    'image': 'assets/images/menu/menu_93.png',
    'name': 'menu93',
    'price': 38000,
    'category': 'category5',
  },
  {
    'id': '94',
    'image': 'assets/images/menu/menu_94.png',
    'name': 'menu94',
    'price': 56800,
    'category': 'category5',
  },
  {
    'id': '95',
    'image': 'assets/images/menu/menu_95.png',
    'name': 'menu95',
    'price': 42800,
    'category': 'category5',
  },
  {
    'id': '96',
    'image': 'assets/images/menu/menu_96.png',
    'name': 'menu96',
    'price': 22800,
    'category': 'category5',
  },
  {
    'id': '97',
    'image': 'assets/images/menu/menu_97.png',
    'name': 'menu97',
    'price': 23800,
    'category': 'category5',
  },
  {
    'id': '98',
    'image': 'assets/images/menu/menu_98.png',
    'name': 'menu98',
    'price': 41800,
    'category': 'category5',
  },
  {
    'id': '99',
    'image': 'assets/images/menu/menu_99.png',
    'name': 'menu99',
    'price': 48800,
    'category': 'category5',
  },
  {
    'id': '100',
    'image': 'assets/images/menu/menu_100.png',
    'name': 'menu100',
    'price': 38000,
    'category': 'category5',
  },
  {
    'id': '101',
    'image': 'assets/images/menu/menu_101.png',
    'name': 'menu101',
    'price': 36800,
    'category': 'category5',
  },
  {
    'id': '102',
    'image': 'assets/images/menu/menu_102.png',
    'name': 'menu102',
    'price': 38000,
    'category': 'category5',
  },
  {
    'id': '103',
    'image': 'assets/images/menu/menu_103.png',
    'name': 'menu103',
    'price': 42000,
    'category': 'category5',
  },
  {
    'id': '104',
    'image': 'assets/images/menu/menu_104.png',
    'name': 'menu104',
    'price': 24800,
    'category': 'category5',
  },
  {
    'id': '105',
    'image': 'assets/images/menu/menu_105.png',
    'name': 'menu105',
    'price': 28000,
    'category': 'category5',
  },
  {
    'id': '106',
    'image': 'assets/images/menu/menu_106.png',
    'name': 'menu106',
    'price': 24800,
    'category': 'category5',
  },
  {
    'id': '107',
    'image': 'assets/images/menu/menu_107.png',
    'name': 'menu107',
    'price': 42000,
    'category': 'category5',
  },
  {
    'id': '108',
    'image': 'assets/images/menu/menu_108.png',
    'name': 'menu108',
    'price': 32000,
    'category': 'category5',
  },
  {
    'id': '109',
    'image': 'assets/images/menu/menu_109.png',
    'name': 'menu109',
    'price': 29800,
    'category': 'category5',
  },
  {
    'id': '110',
    'image': 'assets/images/menu/menu_110.png',
    'name': 'menu110',
    'price': 68000,
    'category': 'category5',
  },
  {
    'id': '111',
    'image': 'assets/images/menu/menu_111.png',
    'name': 'menu111',
    'price': 19800,
    'category': 'category5',
  },
  {
    'id': '112',
    'image': 'assets/images/menu/menu_112.png',
    'name': 'menu112',
    'price': 19800,
    'category': 'category5',
  },
  {
    'id': '113',
    'image': 'assets/images/menu/menu_113.png',
    'name': 'menu113',
    'type': {'0': 'method22', '1': 'method23', '2': 'method24'},
    'price': {'0': 18000, '1': 22800, '2': 18000},
    'category': 'category6',
  },
  {
    'id': '114',
    'image': 'assets/images/menu/menu_114.png',
    'name': 'menu114',
    'type': {'0': 'method22', '1': 'method24', '2': 'method25'},
    'price': {'0': 18000, '1': 18000, '2': 18000},
    'category': 'category6',
  },
  {
    'id': '115',
    'image': 'assets/images/menu/menu_115.png',
    'name': 'menu115',
    'type': {'0': 'method22', '1': 'method24', '2': 'method27'},
    'price': {'0': 18000, '1': 18000, '2': 22800},
    'category': 'category6',
  },
  {
    'id': '116',
    'image': 'assets/images/menu/menu_116.png',
    'name': 'menu116',
    'type': {'0': 'method22', '1': 'method24'},
    'price': {'0': 18000, '1': 18000},
    'category': 'category6',
  },
  {
    'id': '117',
    'image': 'assets/images/menu/menu_117.png',
    'name': 'menu117',
    'type': {
      '0': 'method11',
      '1': 'method24',
      '2': 'method22',
      '3': 'method23'
    },
    'price': {'0': 18000, '1': 18000, '2': 18000, '3': 22800},
    'category': 'category6',
  },
  {
    'id': '118',
    'image': 'assets/images/menu/menu_118.png',
    'name': 'menu118',
    'price': 138000,
    'category': 'category7',
  },
  {
    'id': '119',
    'image': 'assets/images/menu/menu_119.png',
    'name': 'menu119',
    'price': 158000,
    'category': 'category7',
  },
  {
    'id': '120',
    'image': 'assets/images/menu/menu_120.png',
    'name': 'menu120',
    'price': 88000,
    'category': 'category7',
  },
  {
    'id': '121',
    'image': 'assets/images/menu/menu_121.png',
    'name': 'menu121',
    'price': 68000,
    'category': 'category7',
  },
  {
    'id': '122',
    'image': 'assets/images/menu/menu_122.png',
    'name': 'menu122',
    'price': 88000,
    'category': 'category7',
  },
  {
    'id': '123',
    'image': 'assets/images/menu/menu_123.png',
    'name': 'menu123',
    'price': 48000,
    'category': 'category7',
  },
  {
    'id': '124',
    'image': 'assets/images/menu/menu_124.png',
    'name': 'menu124',
    'price': 21800,
    'category': 'category7',
  },
  {
    'id': '125',
    'image': 'assets/images/menu/menu_125.png',
    'name': 'menu125',
    'price': 20800,
    'category': 'category7',
  },
  {
    'id': '126',
    'image': 'assets/images/menu/menu_126.png',
    'name': 'menu126',
    'price': 19800,
    'category': 'category7',
  },
  // {
  //   'id': '127',
  //   'image': 'assets/images/menu/menu_127.png',
  //   'name': '',
  //   'price': 26800,
  //   'category': 'category8',
  // },
  {
    'id': '128',
    'image': 'assets/images/menu/menu_128.png',
    'name': 'menu128',
    'price': 21800,
    'category': 'category8',
  },
  // {
  //   'id': '129',
  //   'image': 'assets/images/menu/menu_129.png',
  //   'name': 'Modern Baba',
  //   'price': 21800,
  //   'category': 'category8',
  // },
  {
    'id': '130',
    'image': 'assets/images/menu/menu_130.png',
    'name': 'menu130',
    'price': 22800,
    'category': 'category8',
  },
  {
    'id': '131',
    'image': 'assets/images/menu/menu_131.png',
    'name': 'menu131',
    'price': 26800,
    'category': 'category8',
  },
  // {
  //   'id': '132',
  //   'image': 'assets/images/menu/menu_132.png',
  //   'name': 'Niuroubing',
  //   'price': 29800,
  //   'category': 'category8',
  // },
  {
    'id': '133',
    'image': 'assets/images/menu/menu_133.png',
    'name': 'menu133',
    'price': 21800,
    'category': 'category8',
  },
  {
    'id': '134',
    'image': 'assets/images/menu/menu_134.png',
    'name': 'menu134',
    'price': 22800,
    'category': 'category8',
  },
  {
    'id': '135',
    'image': 'assets/images/menu/menu_135.png',
    'name': 'menu135',
    'price': 'string_price',
    'category': 'category9',
  },
  {
    'id': '136',
    'image': 'assets/images/menu/menu_136.png',
    'name': 'menu136',
    'type': {'0': 'method28', '1': 'method29'},
    'price': {'0': 30800, '1': 28800},
    'category': 'category9',
  },
  {
    'id': '138',
    'image': 'assets/images/menu/menu_138.png',
    'name': 'menu138',
    'type': {'0': 'method28', '1': 'method29'},
    'price': {'0': 30800, '1': 28800},
    'category': 'category9',
  },
  {
    'id': '140',
    'image': 'assets/images/menu/menu_140.png',
    'name': 'menu140',
    'price': 38000,
    'category': 'category9',
  },
  {
    'id': '141',
    'image': 'assets/images/menu/menu_141.png',
    'name': 'menu141',
    'price': 30800,
    'category': 'category9',
  },
  {
    'id': '142',
    'image': 'assets/images/menu/menu_142.png',
    'name': 'menu142',
    'price': 34800,
    'category': 'category9',
  },
  {
    'id': '143',
    'image': 'assets/images/menu/menu_143.png',
    'name': 'menu143',
    'price': 27000,
    'category': 'category9',
  },
  {
    'id': '144',
    'image': 'assets/images/menu/menu_144.png',
    'name': 'menu144',
    'price': 28000,
    'category': 'category9',
  },
  {
    'id': '145',
    'image': 'assets/images/menu/menu_145.png',
    'name': 'menu145',
    'type': {'0': 'method30', '1': 'method31'},
    'price': {'0': 23800, '1': 6800},
    'category': 'category10',
  },
  // {
  //   'id': '146',
  //   'image': 'assets/images/menu/menu_146.png',
  //   'name': '',
  //   'price': {'0': 28800, '1': 8800},
  //   'category': 'category10',
  // },
  {
    'id': '147',
    'image': 'assets/images/menu/menu_147.png',
    'name': 'menu147',
    'type': {'0': 'method30', '1': 'method31'},
    'price': {'0': 28800, '1': 8800},
    'category': 'category10',
  },
  {
    'id': '148',
    'image': 'assets/images/menu/menu_148.png',
    'name': 'menu148',
    'type': {'0': 'method30', '1': 'method31'},
    'price': {'0': 23800, '1': 6800},
    'category': 'category10',
  },
  {
    'id': '149',
    'image': 'assets/images/menu/menu_149.png',
    'name': 'menu149',
    'type': {'0': 'method30', '1': 'method31'},
    'price': {'0': 28800, '1': 8800},
    'category': 'category10',
  },
  {
    'id': '150',
    'image': 'assets/images/menu/menu_150.png',
    'name': 'menu150',
    'type': {'0': 'method30', '1': 'method31'},
    'price': {'0': 28800, '1': 8800},
    'category': 'category10',
  },
];
